dist: xenial
language: python
cache: pip
python:
  - 3.8
  - pypy3

services:
  - docker
  -
before_deploy:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
